let soundOn=false,watchTimer=null,watchStart=0,watchElapsed=0;
const facts=["HTML gives a webpage its structure.","CSS controls presentation and layout.","JavaScript can make webpages interactive.","Python is widely used for web backends and automation.","The first website went online in 1991.","Small projects are one of the best ways to learn programming.","A browser can run JavaScript without a server."];

window.addEventListener("load",()=>setTimeout(()=>document.getElementById("loader").classList.add("hide"),1500));
document.addEventListener("mousemove",e=>{const g=document.querySelector(".cursor-glow");g.style.left=e.clientX+"px";g.style.top=e.clientY+"px"});
function toggleMenu(){document.getElementById("nav").classList.toggle("open")}
function showToast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function beep(){if(!soundOn)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=520;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.06)}catch{}}
function toggleSound(){soundOn=!soundOn;document.getElementById("soundLabel").textContent="SOUND: "+(soundOn?"ON":"OFF");beep()}
function calc(v){document.getElementById("calc").value+=v;beep()}
function clearCalc(){document.getElementById("calc").value="";document.getElementById("calcOut").textContent="Ready."}
function backCalc(){let x=document.getElementById("calc");x.value=x.value.slice(0,-1)}
function calculate(){let x=document.getElementById("calc").value;try{if(!/^[0-9+\-*/().%\s]+$/.test(x))throw Error();let safe=x.replace(/(\d+(?:\.\d+)?)%/g,"($1/100)");let r=Function('"use strict";return ('+safe+')')();if(!Number.isFinite(r))throw Error();document.getElementById("calcOut").textContent="Answer: "+r;beep()}catch{document.getElementById("calcOut").textContent="Invalid expression."}}
function fact(){document.getElementById("fact").textContent=facts[Math.floor(Math.random()*facts.length)];beep()}
function typing(){let a=document.getElementById("typing").value,b=document.getElementById("phrase").textContent,o=document.getElementById("typingOut");if(a===b)o.textContent="🔥 PERFECT! RUDRA MODE: ONLINE.";else if(b.startsWith(a))o.textContent=a.length+"/"+b.length+" characters";else o.textContent="Keep going — check the phrase."}
function convert(){let v=Number(document.getElementById("unitVal").value),t=document.getElementById("unitType").value;if(!Number.isFinite(v)){document.getElementById("unitOut").textContent="Enter a value.";return}let r=t==="km"?v*.621371:t==="miles"?v*1.609344:t==="c"?v*9/5+32:(v-32)*5/9;document.getElementById("unitOut").textContent="Result: "+r.toFixed(3)}
function startWatch(){if(watchTimer)return;watchStart=Date.now()-watchElapsed;watchTimer=setInterval(()=>{watchElapsed=Date.now()-watchStart;let s=watchElapsed/1000;document.getElementById("watch").textContent=s.toFixed(1).padStart(4,"0")},100)}
function stopWatch(){clearInterval(watchTimer);watchTimer=null}
function resetWatch(){stopWatch();watchElapsed=0;document.getElementById("watch").textContent="00:00.0"}
function askAI(){let i=document.getElementById("aiInput"),q=i.value.trim().toLowerCase(),c=document.getElementById("chat");if(!q)return;let r=q.includes("/help")?"Commands: /about /skills /projects /creator":q.includes("/about")?"I'm Vicky AI Core — a local interactive assistant for Rudra's website.":q.includes("/skills")?"Current learning: HTML, CSS, JavaScript and Python.":q.includes("/projects")?"Projects: Future Tech Hub, Askora AI and Calculator Vault.":q.includes("/creator")?"Creator identity: Bikkee Warrior.":q.includes("hello")?"Hello! Welcome to Rudra's Tech Lab.":"Try /help, /about, /skills, /projects or /creator.";c.innerHTML+="<p><b>YOU:</b> "+escapeHTML(i.value)+"</p><p>VICKY AI: "+r+"</p>";i.value="";c.scrollTop=c.scrollHeight}
function escapeHTML(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function terminalKey(e){if(e.key!=="Enter")return;let i=document.getElementById("termIn"),q=i.value.trim().toLowerCase(),o=document.getElementById("termOut"),r={help:"Commands: help, whoami, about, skills, projects, youtube, status, secret, clear, date",whoami:"Rudra Pratap Singh // Vicky",about:"Student developer learning by building.",skills:"HTML • CSS • JavaScript • Python (learning)",projects:"Future Tech Hub • Askora AI • Calculator Vault",youtube:"Bikkee Warrior",status:"LEARNING → BUILDING → IMPROVING",date:new Date().toLocaleString(),secret:""}[q];if(q==="clear"){o.innerHTML="";i.value="";return}if(q==="secret"){secretMode();i.value="";return}o.innerHTML+="<p>› "+escapeHTML(i.value)+"</p><p>"+(r||"Command not found. Type help.")+"</p>";i.value="";o.scrollTop=o.scrollHeight}
function secretMode(){document.body.classList.add("secret");showToast("🚀 RUDRA SECRET MODE ACTIVATED");setTimeout(()=>document.body.classList.remove("secret"),3500);beep()}
document.addEventListener("keydown",e=>{if(e.key==="Enter"&&document.activeElement.id==="calc")calculate()})
